#
# Copyright © 2016-2018 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app: as-elasticsearch
  name: as-elasticsearch
spec:
  type: NodePort
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    interface: as-elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: as-elasticsearch
spec:
  serviceName: as-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: as-elasticsearch
  template:
    metadata:
      labels:
        app: as-elasticsearch
        interface: as-elasticsearch
    spec:
      containers:
      - image: elasticsearch:6.5.4
        name: audit-service-elasticsearch
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: as-esdata
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "ES_JAVA_OPTS"
          value: "-XX:-AssumeMP"
        - name: cluster.name
          value: audit_service
        - name: node.name
          value: es01
  volumeClaimTemplates:
    - metadata:
        name: as-esdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 10Gi

