apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-spark
spec:
  capacity:
    storage: 10G 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: /nfs/testcluster/egys-pg-test-fabo-pvc-e67e596f-82d3-11e9-aea0-566f555f002a
    server: 10.151.102.106
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem
