---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-ui
  name: spark-ui
spec:
  type: NodePort
  ports:
  - name: public
    port: 18080
  selector:
    interface: spark-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-ui
  template:
    metadata:
      labels:
        app: spark-ui
        interface: spark-ui
    spec:
      containers:
      - name: spark-ui
        image: dockerepo.dc01.havelsan.io/afis/eternnoir/ubuntu-java:oracle-java8
        command: ['sh', '-c', 'sleep 36000']
        ports:
        - containerPort: 18080
          name: public
        volumeMounts:
        - mountPath: "/tmp/spark-events"
          name: mypd
      volumes:
      - name: mypd
        persistentVolumeClaim:
         claimName: spark-claim    