kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracle-pvc
  namespace: evreka
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi
  storageClassName: nfs
