#
# Copyright © 2016-2018 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
apiVersion: v1
kind: Service
metadata:
  name: egys-service
  namespace: egys
  labels:
    app: egys-service
spec:
  ports:
  - port: 8080
    name: ui
    nodePort: 31080
  - port: 1883
    name: mqtt
  - port: 5683
    name: coap
    protocol: UDP
  selector:
    app: egys
  type: NodePort
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: egys-budget
  namespace: egys
spec:
  selector:
    matchLabels:
      app: egys
  minAvailable: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: egys-config
  namespace: egys
data:
  zookeeper.enabled: "false"
  zookeeper.url: "zk-headless"
  cassandra.url: "bitcass-cassandra-headless:9042"
  cassandra.host: "bitcass-cassandra-headless"
  #cassandra.url: "10.151.16.159:9042"
  #cassandra.host: "10.151.16.159"
  cassandra.port: "9042"
  database.ts.type: "cassandra"
  database.entities.type: "cassandra"
  cache.type: "redis"
  redis.host: "redis-service"
  ui-port: "8080"
  add_schema_and_system_data: "false"
  add_demo_data: "false"
  update_system_widgets: "false"
  db-user: "cassandra"
  db-password: "cassandra"
  db-cred: "true"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: egys
  namespace: egys
spec:
  serviceName: "egys-service"
  replicas: 2
  template:
    metadata:
      labels:
        app: egys
    spec:
#      nodeSelector:
#        machinetype: egys
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - egys-service
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: egys
        imagePullPolicy: IfNotPresent
        image: thingsboard/application:2.1.0
        #        image: 10.151.17.110/botas/egys:2.1.1
        ports:
        - containerPort: 8080
          name: ui
        - containerPort: 1883
          name: mqtt
        - containerPort: 5683
          name: coap
        - containerPort: 9001
          name: rpc
        env:
#        - name: ZOOKEEPER_ENABLED
#          valueFrom:
#            configMapKeyRef:
#              name: egys-config
#              key: zookeeper.enabled
#        - name: ZOOKEEPER_URL
#          valueFrom:
#            configMapKeyRef:
#              name: egys-config
#              key: zookeeper.url
        - name : CASSANDRA_HOST
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: cassandra.host
        - name : CASSANDRA_PORT
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: cassandra.port
        - name : CASSANDRA_URL
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: cassandra.url
        - name: DATABASE_TS_TYPE
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: database.ts.type
###### SADECE TB DENEMESI ICIN  CIKAR SERKAN
        - name: DATABASE_TYPE
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: database.entities.type
###### SADECE TB DENEMESI ICIN  CIKAR SERKAN
        - name: DATABASE_ENTITIES_TYPE
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: database.entities.type
        - name : RPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
#        - name: CACHE_TYPE
#          valueFrom:
#            configMapKeyRef:
#              name: egys-config
#              key: cache.type
#        - name: REDIS_HOST
#          valueFrom:
#            configMapKeyRef:
#              name: egys-config
#              key: redis.host
        - name: UPDATE_SYSTEM_WIDGETS
          valueFrom:
             configMapKeyRef:
               name: egys-config
               key: update_system_widgets
        - name: ADD_SCHEMA_AND_SYSTEM_DATA
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: add_schema_and_system_data
        - name: ADD_DEMO_DATA
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: add_demo_data
        - name: CASSANDRA_USE_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: db-cred
        - name: CASSANDRA_USERNAME
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: db-user
        - name: CASSANDRA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: egys-config
              key: db-password
        command:
        - sh
        - -c
        - /run-application.sh
        livenessProbe:
          httpGet:
            path: /login
            port: ui
          initialDelaySeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet: # make an HTTP request
            port: ui # port to use
            path: /login # endpoint to hit
            scheme: HTTP # or HTTPS
          initialDelaySeconds: 3 # how long to wait before checking
          periodSeconds: 3 # how long to wait between checks
          successThreshold: 1 # how many successes to hit before accepting
          failureThreshold: 1 # how many failures to accept before failing
          timeoutSeconds: 1
