apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocrbot
  namespace: evreka
spec:
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  # revisionHistoryLimit: 4
  # paused: false
  replicas: 1
  minReadySeconds: 40
  selector:
    matchLabels:
      role: ocrbot
  template:
    metadata:
      name: ocrbot
      labels:
        app: ocrbot
        role: ocrbot
        version: v1.3.5
    spec:
      imagePullSecrets:
      - name: harbor
      containers:
      - name: ocrbot
        image: 10.151.17.110/edbys/ocrboot:1.3.5
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"        
        ports:
          - containerPort: 4000
            name: ocrbot-port
            protocol: TCP