#
# Copyright © 2016-2018 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: as-cassandra-np
  name: as-cassandra-np
spec:
  type: NodePort
  ports:
    - port: 9142
      name: cql
  selector:
    interface: as-cassandra

---

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: as-cassandra-headless
  name: as-cassandra-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9142
      targetPort: 9042
      name: cql
  selector:
    interface: as-cassandra

---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: as-cassandra
spec:
  serviceName: as-cassandra-headless
  replicas: 1
  selector:
    matchLabels:
      app: as-cassandra
  template:
    metadata:
      labels:
        app: as-cassandra
        interface: as-cassandra
    spec:
      containers:
        - name: as-cassandra
          image: dockerepo.dc01.havelsan.io/botas/cassandra:3.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_SEEDS
              value: as-cassandra-0.as-cassandra-headless.egys.svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "EGYS Cluster"
            - name: CASSANDRA_DC
              value: "egys-dc"
            - name: CASSANDRA_RACK
              value: "egys-rack"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          volumeMounts:
            - name: as-cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: as-cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 10Gi
