kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cm-pvc
  namespace: evreka
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cm-tmpfs-pvc
  namespace: evreka
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
