VAGRANTFILE_API_VERSION = "2"

$k8s_count=4

$k8s_memory=4096
$k8s_cpus=1

def workerIP(num)
  return "172.17.8.#{num+100}"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  config.ssh.username = 'root'
  config.ssh.password = 'root'
  config.ssh.insert_key = 'true'
config.vm.box = "bento/ubuntu-16.04"
  (1..$k8s_count).each do |i|
    config.vm.define vm_name = "k8s-0%d" % i do |node|
      node.vm.network :private_network, :ip => "#{workerIP(i)}"
      node.vm.hostname = vm_name
      node.vm.provider "virtualbox" do |v|
        v.memory = $k8s_memory
        v.cpus = $k8s_cpus
      end
      node.vm.provision :shell, :inline => "sed 's/127.0.0.1.*k8s-0#{i}/#{workerIP(i)} k8s-0#{i}/' -i /etc/hosts"
      node.vm.provision :shell, :path => "bootstrap.sh"
    end
  end
end
