call plug#begin('~/.vim/plugged')
	Plug 'scrooloose/nerdtree'
	Plug 'tpope/vim-fugitive'
	Plug 'tpope/vim-sensible'
	Plug 'tpope/vim-surround'
	Plug 'tomasr/molokai'
	Plug 'ap/vim-css-color'
	Plug 'flazz/vim-colorschemes'
	Plug 'terryma/vim-multiple-cursors'

" Initialize plugin system
call plug#end()

let g:molokai_original = 1

