apiVersion: v1
kind: Service
metadata:
  labels:
    app: midas-thingsboard
  name: midas-thingsboard
spec:
  type: NodePort
  ports:
  - name: public
    port: 8081
  selector:
    app: midas-thingsboard-connector
