#
# Copyright © 2016-2018 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: midas-thingsboard-connector
  name: midas-thingsboard-connector
spec:
  type: NodePort
  ports:
  - name: "public"
    nodePort: 31040
    port: 8081
  selector:
    interface: midas-thingsboard-connector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: midas-thingsboard-connector
  name: midas-thingsboard-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: midas-thingsboard-connector
  template:
    metadata:
      labels:
        app: midas-thingsboard-connector
    spec:
      containers:
      - command:
        - /run-application.sh
        env:
        - name: MIDAS_HOST
          value: mtc-kafka
        - name: MIDAS_PORT
          value: "9192"
        - name: THINGSBOARD_HOST
          value: egys-service
        - name: THINGSBOARD_PASSWORD
          value: "1234"
        - name: THINGSBOARD_PORT
          value: "8080"
        - name: THINGSBOARD_USER
          value: "foas_tenant@havelsan.com.tr"
        image: dockerepo.havelsan.io/botas/egys/midas-thingsboard-connector:1.0.2
        name: midas-thingsboard-connector
        ports:
        - containerPort: 8081
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
