#
# Copyright © 2016-2018 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mtc-postgres-np
  name: mtc-postgres-np
spec:
  type: NodePort
  ports:
    - port: 5432
      name: psql
  selector:
    interface: mtc-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mtc-postgres
  name: mtc-postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      name: psql
  selector:
    interface: mtc-postgres

---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: mtc-postgres
spec:
  serviceName: mtc-postgres
  replicas: 1
  selector:
    matchLabels:
      app: mtc-postgres
  template:
    metadata:
      labels:
        app: mtc-postgres
        interface: mtc-postgres
    spec:
      containers:
        - name: mtc-postgres
          image: postgres:9.6
          env:
            - name: POSTGRES_DB
              value: test_midas
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - name: mtc-postgres-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: mtc-postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 10Gi
