kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: edbysvs-pvc
  namespace: evreka
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
