apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: cp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: solsson/kafka-manager@sha256:28b1a0b355f3972a9e3b5ac82abcbfee9a72b66a2bfe86094f6ea2caad9ce3a7
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          #  value: zookeeper.kafka:2181
          value: my-confluent-oss-cp-zookeeper
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
