kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: cp
spec:
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32480
  type: NodePort
