kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-data-cassandra-0
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-commitlog-cassandra-0
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

