apiVersion: v1
kind: Service
metadata:
  labels:
    app: ffmpeg-server
  name: ffmpeg-server
spec:
  type: NodePort
  ports:
  - name: public
    port: 8001
  selector:
    interface: ffmpeg-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffmpeg-server
  template:
    metadata:
      labels:
        app: ffmpeg-server
        interface: ffmpeg-server
    spec:
      containers:
      - name: ffmpeg-server
        image: dockerepo.dc01.havelsan.io/botas/egys/camera-manager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
          name: public
      restartPolicy: Always
