---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-test-headless
  name: cassandra-test-headless
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql
  selector:
    interface: cassandra-test

---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra-test
spec:
  serviceName: cassandra-test-headless
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-test
  template:
    metadata:
      labels:
        app: cassandra-test
        interface: cassandra-test
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: dc
#                operator: In
#                values:
#                - DC1
      containers:
        - name: cassandra-test
          image: cassandra:3.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_SEEDS
              # SERKAN value: cassandraa-0.cassandraa.c7a.svc.cluster.local,cassandrab-0.cassandrab.c7a.svc.cluster.local
              value: cassandra-test-0.cassandra-test-headless.default.svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Test Cluster"
            - name: CASSANDRA_DC
              # SERKAN value: "DC1-Thingsboard-Cluster"
              value: "datacenter1"
            - name: CASSANDRA_RACK
              # SERKAN value: "Rack-Thingsboard-Cluster"
              value: "rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
