---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgis
  name: postgis
spec:
  type: NodePort
  ports:
    - port: 5432
      name: psql
  selector:
    interface: postgis

---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: postgis
spec:
  serviceName: postgis
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
        interface: postgis
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: dc
#                operator: In
#                values:
#                - DC1
      containers:
        - name: postgis
          image: postgis/9.5-2.2:latest
          env:
            - name: ALLOW_IP_RANGE
              value: 0.0.0.0/0
            - name: POSTGRES_USER
              value: postgres1
            - name: POSTGRES_PASSWORD
              value: postgres1 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgis-data
#        annotations:  # comment line if you want to use a StorageClass
#          volume.beta.kubernetes.io/storage-class: ""
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 10Gi
          # or specify which StorageClass
