apiVersion: apps/v1
kind: Deployment
metadata:
  name: sablon
  namespace: evreka
spec:
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  # revisionHistoryLimit: 4
  # paused: false
  replicas: 1
  minReadySeconds: 40
  selector:
    matchLabels:
      role: sablon
  template:
    metadata:
      name: sablon
      labels:
        app: sablon
        role: sablon
        version: 1.2.33
    spec:
      # imagePullSecrets:
      # - name: harbor
      containers:
      - name: sablon
        image: 10.151.17.110/edbys/gk-sablon:1.2.33
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"        
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5050
            name: sablon-port-1
            protocol: TCP
          - containerPort: 9595
            name: sablon-port-2
            protocol: TCP
        volumeMounts:
        - name: sablon-vol
          mountPath: /external/resources
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: sablon-vol
        persistentVolumeClaim:
          claimName: sablon-pvc
      - name: tz-config
        hostPath:
          path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: sablon
  namespace: evreka
  labels:
    role: sablon
spec:
  selector:
    role: sablon
  ports:
    - port: 5050
      name: sablon-port-1
      targetPort: sablon-port-1
    - port: 9595
      name: sablon-port-2
      targetPort: sablon-port-2
  type: NodePort