apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: metallb-nginx
spec:
  selector:
    matchLabels:
      app: metallb-nginx
  template:
    metadata:
      labels:
        app: metallb-nginx
    spec:
      containers:
      - name: metallb-nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: metallb-nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: metallb-nginx
  type: LoadBalancer
