dependencies:
  - name: mariadb
    version: 0.6.0
    repository: https://kubernetes-charts.storage.googleapis.com
  
  - name: cassandra
    version: 2.3.3
    repository: https://charts.bitnami.com/bitnami
