apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfsserver-nfs-server-provisioner-0
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/volumes/data-nfsserver-nfs-server-provisioner-0
  claimRef:
    # namespace: kube-system
    namespace: storage
    name: data-nfsserver-nfs-server-provisioner-0
